# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WCwnuXtvpwP1WvLROznJOzGI0ntBb9C
"""

!pip install qiskit qiskit-aer

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt

# Create circuit with 2 qubits and 2 classical bits
qc = QuantumCircuit(2, 2)

# Put first qubit into superposition
qc.h(0)

# Entangle second qubit with first qubit
qc.cx(0, 1)

# Measure both qubits
qc.measure([0, 1], [0, 1])

# Run simulation
simulator = AerSimulator()
result = simulator.run(qc, shots=1024).result()

# Get results
counts = result.get_counts()

# Print measurement results
print("Measurement Results:")
print(counts)

# Display histogram
plot_histogram(counts)
plt.show()

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

# Create 1 qubit and 1 classical bit
qc = QuantumCircuit(1, 1)

# Put qubit into superposition
qc.h(0)

# Measure qubit
qc.measure(0, 0)

# Run simulation
simulator = AerSimulator()
result = simulator.run(qc, shots=1).result()

counts = result.get_counts()

print("Random Result:")
print(counts)